### ISSUE TITLE
feature: Enable usb-otg for Pi4

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#1020]
Useful to use the same cable as for network interface and power the Pi
E.g: https://forums.raspberrypi.com/viewtopic.php?t=243966

**Comment by Williangalvani** [comment]
tips:

/boot/cmdline.txt:
`modules-load=dwc2,g_ether`

/boot/config.txt:
`dtoverlay=dwc2,dr_mode=peripheral`

make sure there is something in [beacon's default advertising list](https://github.com/bluerobotics/BlueOS-docker/blob/master/core/services/beacon/default-settings.json#L4), or add an entry for usb0 in the config

**Comment by Williangalvani** [comment]
also, I didnt get an ip on that interface straight away, so I set a static one in the 169.254 range
