### ISSUE TITLE
bug: Bridges should use serial by-path and not by /dev/name

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#1024]
### Bug description

The numbers under `/dev/name` will not be consistent between boots, it's safer to use by-path values to access the devices; 

### Steps to reproduce

Reboot with multiple serial devices connected, or connect and disconnect a serial device on the same port while a program is running. 

### Primary pain point(s)

This makes the connection with such devices inconsistent. 

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
Duplicate of #1017?

**Comment by patrickelectric** [comment]
my fault.
