### ISSUE TITLE
system-information: fetch fail on start

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1101]
Noticed today that anytime I restart BlueOS the following notification is sent:

<img width="517" alt="image" src="https://user-images.githubusercontent.com/6551040/182437943-592553e2-c8db-4dad-8e7d-26ec34992e2a.png">

@patrickelectric seems like something related to the recent Linux2Rest changes.

**Comment by patrickelectric** [comment]
Thanks! I'll take a look.

**Comment by rafaellehmkuhl** [comment]
More info:

<img width="1186" alt="image" src="https://user-images.githubusercontent.com/6551040/182464994-cc49f20a-8c03-4bc0-a582-993ddbbb6bdc.png">
