### ISSUE TITLE
core: frontend: Version chooser showing "upgrade" to an older version

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#1131]
### Current behaviour

When turning off pirate mode, version chooser shows "upgrade" to an old version.
![image](https://user-images.githubusercontent.com/1215497/188003702-317832f5-571c-4bb8-bbd6-a9a1b5e5da7d.png)

### Expected or desired behaviour

We should show "revert" or "downgrade"

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
Strange. This seems more like a bug somewhere. We don't offer downgrades.
