### ISSUE TITLE
hotspot: MDNS for hotspot does not work

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1138]
Accessing directly with the hotspot IP (192.168.42.1) everything works fine, but the MDNS (blueos-hotspot.local) does not.
Apparently I forgot to add a new version of the beacon settings.

Reported by @ES-Alexander

**Comment by Williangalvani** [comment]
I believe this was fixed in https://github.com/bluerobotics/BlueOS-docker/pull/1145
