### ISSUE TITLE
bug: Resetting Video Manager settings causes timeout exceeded message

### ISSUE THREAD

**Issue by dgudiel** [bluerobotics/BlueOS-docker#1171]
### Bug description

Every time I reset settings in Video Manager Settings it causes a timeout of 1000ms exceeded message. 
![image](https://user-images.githubusercontent.com/20758859/195475929-8829494f-2641-4366-855e-ea8a6f0dbb52.png)

### Steps to reproduce

1. Go to Video menu
2. Click on settings
3. Click on Reset Settings

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
@patrickelectric that is with you or @joaoantoniocardoso right?

**Comment by patrickelectric** [comment]
I'll take a look.
