### ISSUE TITLE
camera-manager: provide SDP files for video streams

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-docker#1195]
### Current behaviour

Companion Software used to provide an SDP file for easily connecting to a video stream from applications like VLC. BlueOS does not do this, which is inconvenient for people who are used to using it.

### Expected or desired behaviour

Provide links / easy access to sdp files, ideally for all video streams, but at least for those with H264 encoding.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by joaoantoniocardoso** [comment]
@patrickelectric should we add it for the next release? MVM side is ready.
