### ISSUE TITLE
core: camera-manager: allow hot-plugging cameras

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-docker#1203]
### Current behaviour

When a camera is un-plugged it is quite quickly removed from the frontend interface, but when a new camera is plugged in (or the previous one is plugged back in) it does not appear until the onboard computer is rebooted. That generally isn't an issue for operation (in which case cameras are usually connected before the vehicle is turned on), but can be annoying during development / testing.

Feature was asked about in [this forum post](https://discuss.bluerobotics.com/t/finding-camera-after-boot/13115).

### Expected or desired behaviour

Ideally cameras could be freely plugged in and removed, and the UI would display the current cameras that are available.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
reference: https://github.com/mavlink/mavlink-camera-manager/issues/206
