### ISSUE TITLE
core: frontend: parameters: improve edit UI/UX

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-docker#1212]
### Current behaviour

- `Max` is shown before `Min`, which is unintuitive
- Horizontal spacing between Max and Min is small
- Vertical spacing between restrictions row and description row is small
- Increment is not considered

### Expected or desired behaviour

- [ ] Restrictions row should show something like
   **Min:** -0.5 &nbsp;&nbsp;&nbsp; **Max:** 3.5 &nbsp;&nbsp;&nbsp; **Increment:** 0.01
   - Not sure how to do the spacing, but I expect an increment is only ever present if there's also a range, so perhaps something like
      ```html
      <v-row v-if="edited_param.range">
        Min: {{ edited_param.range.low }}
        Max: {{ edited_param.range.high }}
        <span v-if="edited_param.increment">
          Increment: {{ edited_param.increment }}
        </span>
      </v-row>
      ```
- [ ] Vertical spacing should be increased between restrictions row and description
   - [ ] Possibly also put description first, so restrictions are shown directly above the interface that's changing the value
      - If description is first, I'm not sure if it's better to have `Reboot Required` above or below the description
- [ ] Ideally increment should be validated
   - Noting that [that may be a bit of effort](https://github.com/bluerobotics/BlueOS-docker/pull/806#issuecomment-1302122169), especially since values are floats, and some parameters (e.g. `AHRS_TRIM_*`) have ranges that mean increment can't just be checked directly with a modulo
   - It'd need to be something like `isclose((value - range_min) % increment, 0)`

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
I'm not sure if increment should be validated, it's more an hint than a rule.
