### ISSUE TITLE
Add instructions for how to share topside internet to the ROV.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#1280]

**Comment by patrickelectric** [comment]
https://pureinfotech.com/share-internet-connection-windows-10/#:~:text=Share%20internet%20through%20Ethernet%20on%20Windows%2010&text=Click%20on%20Status.,the%20Change%20adapter%20options%20button.&text=Right%2Dclick%20the%20adapter%20with,Click%20the%20Sharing%20tab.

**Comment by ES-Alexander** [comment]
Marking this as duplicate (even though it's the original) since the new one has significantly more details.
