### ISSUE TITLE
Create branch/action that includes latest camera manager and cockpit 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#1315]

**Comment by ES-Alexander** [comment]
@patrickelectric is this still relevant now that cockpit is available as an extension? IIRC we ended up merging in the webrtc camera manager too, but I may be misremembering.

**Comment by patrickelectric** [comment]
We don't have latest/master releases as extensions available on BlueOS, @Williangalvani, but at least cockpit is deploying it.
