### ISSUE TITLE
Version Chooser offers to "Download and Apply" version already running

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1391]
<img width="1032" alt="image" src="https://user-images.githubusercontent.com/6551040/214107207-df859c7e-57be-4e19-9abb-2a3ce6e29b2b.png">

@Williangalvani

**Comment by ES-Alexander** [comment]
Was this specifically an issue because the `sha` wasn't being detected, so `N/A` is different to `fac26946`?
If so, I believe it should have been fixed (in more recent versions) by #1387
