### ISSUE TITLE
Version Chooser think that a image with the same name as the current (but not the same) is running

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1392]
Notice I have a running image called "master", and I have in my disk a (very old) image also called master, but with a different SHA and from a different repo, but Version Chooser thinks they are the same and that both are running.

<img width="1032" alt="image" src="https://user-images.githubusercontent.com/6551040/214107580-688138f8-d065-447d-a34c-6da9444d7d4e.png">

@Williangalvani

**Comment by ES-Alexander** [comment]
You've already reported this in #1033.

This is what that "I have checked to make sure that a similar request has not already been filed or fixed." checkbox is for in the issue template :-P

**Comment by rafaellehmkuhl** [comment]
> 

Damn kkk
