### ISSUE TITLE
Extension manager offers downgrade (to 0.0.0)

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1418]
![image](https://user-images.githubusercontent.com/6551040/215611618-5997d2b5-8e9f-440f-9856-20b1a1bb52e2.png)

**Comment by joaoantoniocardoso** [comment]
Also mentioned [here](https://github.com/bluerobotics/BlueOS-docker/issues/1398).

**Comment by rafaellehmkuhl** [comment]
> I could not replicate this. any directions?

Really don't know.
I had just instaled latest BlueOS master and installed zerotier after that.
Maybe it's worth mentioning that I use to have zerotier before the update that removed all installed extensions.

**Comment by joaoantoniocardoso** [comment]
> I could not replicate this. any directions?

[The video posted here](https://github.com/bluerobotics/BlueOS-docker/issues/1398) might give you some reproducible path

**Comment by patrickelectric** [comment]
Is this fixed ? @Williangalvani

**Comment by Williangalvani** [comment]
yes
