### ISSUE TITLE
Version Chooser: can't update - "Invalid version: master"

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1423]
Can't update from [heads/master-0-gbddcf49](https://github.com/bluerobotics/blueos-docker/tree/bddcf49)

This is a very _thin_ bug - if you are in master and not in pirate mode, the Version Chooser keeps the spinning wheel as if it would be capable of updating from it, but apparently, it doesn't know 'master':

![image](https://user-images.githubusercontent.com/5920286/215833014-59adaad3-c5f2-4d57-9982-a959ba4da1a4.png)

**Comment by Williangalvani** [comment]
I think it previously tried to get the user back to stable version. we should update the logic there so it allows updating to the new version of the same tag
