### ISSUE TITLE
Video thumbnail appears black

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#1438]
It appears that thumbnails are not working with latest master,
can anyone else confirm that ?

@Williangalvani @joaoantoniocardoso @rafaellehmkuhl

**Comment by joaoantoniocardoso** [comment]
I couldn't reproduce it, but it's probably a problem in mavlink-camera-manager. AFAIR @rafaellehmkuhl had a similar case where the preview was white instead, right?

**Comment by patrickelectric** [comment]
Fixed by connecting and connecting the CSI cable.
