### ISSUE TITLE
Vehicle setup: Enclosure is opaque when first loaded [chrome only]

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1455]
While the enclosure is always transparent in Firefox, it's opaque when first loaded in Chrome:

https://user-images.githubusercontent.com/5920286/217559224-0ff5a6ce-d549-4d1a-a513-642ec090f913.mp4

```
Google Chrome | 110.0.5481.77 (Official Build) (64-bit)
Revision | 65ed616c6e8ee3fe0ad64fe83796c020644d42af-refs/branch-heads/5481@{#839}
OS | Linux
JavaScript | V8 11.0.226.13
User Agent | Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/110.0.0.0 Safari/537.36
```

**Comment by patrickelectric** [comment]
I have the same behavior here, but I believe that's more an issue related to the 3D render than from our side

**Comment by Williangalvani** [comment]
it is actually on our side, it is a side effect of how we hide/show parts. I'll get it fixed soon.
