### ISSUE TITLE
Extension-manager: Menu item not available after updating an extension

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1566]
My BlueOS was with Cockpot v0.0.3 installed, and I could access it from the left menu. 

After update from v0.0.3 to v0.0.4, I can no longer access it from the left menu:
![image](https://user-images.githubusercontent.com/5920286/228598348-78f9e8ad-05cf-43cf-a97a-1027e040c3c6.png)

But after uninstalling it and installing again:
![image](https://user-images.githubusercontent.com/5920286/228598165-63367b9a-9e84-46d2-8fbb-fcad25af1cd0.png)

**Comment by rafaellehmkuhl** [comment]
Duplicated of #1549 probably.

**Comment by patrickelectric** [comment]
did you try to restart BlueOS ?

**Comment by rafaellehmkuhl** [comment]
@Williangalvani @patrickelectric I can confirm this is happening for other extensions as well.

**Comment by patrickelectric** [comment]
I have the same problem

**Comment by Williangalvani** [comment]
same. it seems like the container is coming back with no ports
![image](https://user-images.githubusercontent.com/4013804/231277744-643e1395-630b-49d6-8d70-f59b764c73ce.png)

**Comment by Williangalvani** [comment]
[this](https://github.com/bluerobotics/BlueOS-docker/blob/master/core/services/kraken/kraken.py#L178) seems to be to blame
