### ISSUE TITLE
ParameterEditor: Save button does not get enabled after changing item in list

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#1662]
a parameter such as ARMING_CHECK fails to enable the save button once edited

**Comment by Williangalvani** [comment]
related to #1562

**Comment by clydemcqueen** [comment]
I'm seeing this behavior again on beta 28. I can't change LOG_DISARMED from Disabled to Enabled.

I also tried to change it via "custom" and it did not work.

This seems to affect all parameters.

![image](https://github.com/bluerobotics/BlueOS/assets/4961326/851618e9-e7a8-4941-8a04-c08ff23b5d00)

BlueOS Version: [tags/1.1.0-beta.28-0-g2df6ae03](https://github.com/bluerobotics/blueos-docker/releases/tag/1.1.0-beta.28)
Bootstrap Version: 1.0.1
Build: 8/12/2023, 8:51:38 PM
By [Blue Robotics](https://bluerobotics.com/)

Board name:
Pixhawk1
Manufacturer:
ArduPilot
Mavlink platform:
Pixhawk1
Firmware version:
4.1.0 (STABLE)
Vehicle type:
Submarine
Path:
/dev/ttyACM0
