### ISSUE TITLE
frontend: links to extension are broken

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#1704]
![image](https://github.com/bluerobotics/BlueOS-docker/assets/4013804/eb2610f8-a381-42be-b5c1-4ffaec234d6e)

**Comment by Williangalvani** [comment]
try cockpit:
[Screencast from 2023-05-25 13-53-12.webm](https://github.com/bluerobotics/BlueOS-docker/assets/4013804/3e070a0c-3c0b-42cd-9f59-8dce644f9458)

**Comment by joaoantoniocardoso** [comment]
still broken, but in a different way

![image](https://github.com/bluerobotics/BlueOS-docker/assets/5920286/e071fd0a-63a6-4c20-a3ed-a859fb141814)

**Comment by Williangalvani** [comment]
@joaoantoniocardoso can you double check your master is docker 4dab309e? git BlueOS Version: [heads/master-0-gd5287b99](https://github.com/bluerobotics/blueos-docker/tree/d5287b99)

**Comment by joaoantoniocardoso** [comment]
My bad, this was indeed solved by that PR, I was testing the yesterday's image.
