### ISSUE TITLE
[wizard] Retry not working

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1720]
https://github.com/bluerobotics/BlueOS-docker/assets/5920286/a3494188-a160-4496-b857-ab6e9e23ce32

**Comment by RaulTrombin** [comment]
Same here, testing on:
Fresh install BlueOS Version 1.0.1

![image](https://github.com/bluerobotics/BlueOS-docker/assets/80598030/b5a4de89-d706-473a-ad86-38f43a98b554)
Retry not working.

This one with Reset Settings and reboot.
![image](https://github.com/bluerobotics/BlueOS-docker/assets/80598030/b1e84598-d7a7-403c-a5d2-09f3703b72d8)


But here it works:
![image](https://github.com/bluerobotics/BlueOS-docker/assets/80598030/bfc4c3bb-1b7a-4082-a408-2684c14cc380)

**Comment by Williangalvani** [comment]
the current wizard executes the promises in the wrong step, which means they run as soon as they are created, and the "retry" button just recreates the list with the already resolved promises
