### ISSUE TITLE
[wizard] Wizard should be disable only when succeeded

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1721]
The last step of the wizard, which disables the wizard, should be done after all others were finished with success, otherwise, we can end up with a partially configured vehicle.

Example:

https://github.com/bluerobotics/BlueOS-docker/assets/5920286/ce2715c9-2b85-47c1-946e-26407e1e7deb

**Comment by patrickelectric** [comment]
I think that we should have an option in settings to open the wizard back again.
The main problem is wizard opening everytime someone turns on the ROV.

**Comment by joaoantoniocardoso** [comment]
> I think that we should have an option in settings to open the wizard back again. The main problem is wizard opening everytime someone turns on the ROV.

My point is -- when the step to disable the wizard is run, can we ensure that the vehicle is ready to be used?
