### ISSUE TITLE
[wizard] Error: Failed to install firmware: Error: timeout of 30000ms exceeded.

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1722]
The wizard is failing to download the firmware every time here.

It also shows `Could not set hostname: Request failed with status code 500. ` on the bottom as a notification.

![image](https://github.com/bluerobotics/BlueOS-docker/assets/5920286/e0675270-fa33-4b3d-bb35-4fc096003e5e)

**Comment by patrickelectric** [comment]
can you provide the steps to replicate ?

**Comment by joaoantoniocardoso** [comment]
1. Reset settings
2. follow the wizard

https://github.com/bluerobotics/BlueOS-docker/assets/5920286/a5ca00bf-f3e3-4b55-a2bb-6db188192249

**Comment by joaoantoniocardoso** [comment]
Note that I'm using Raspberry Pi 3 and Pixhawk, on latest master

**Comment by Williangalvani** [comment]
this is also related to #1720. the promises are running before we have internet, I think.
