### ISSUE TITLE
[autopilot firmware] firmware is installed but says 'request failed with code 504'

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1726]
https://github.com/bluerobotics/BlueOS-docker/assets/5920286/e87edc8b-9132-4cd7-aac5-e3c619ffcf9d

**Comment by Williangalvani** [comment]
that is a gateway timeout. I'm guessing nginx is timing out waiting for the flash process to finish. is this easily replicable?
