### ISSUE TITLE
[autopilot firmware] Default firmware for Sub is DEV, but should be.. the latest STABLE?

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1729]
https://github.com/bluerobotics/BlueOS-docker/assets/5920286/e116c4a0-81a9-4bad-b5d2-8aa04dcee752

**Comment by joaoantoniocardoso** [comment]
We should also check the other vehicle types

**Comment by patrickelectric** [comment]
@Williangalvani 
Right now wizard install latest stable

**Comment by joaoantoniocardoso** [comment]
> @Williangalvani Right now wizard install latest stable

Should unify the source of this version, so we guarantee both do the same?

**Comment by Williangalvani** [comment]
I think the wizard goes online to fetch it, I think we need it to be always available offline.
I'd put it into Autopilotmanager or userdata. or both. Look in userdata and fallback to Autopilotmanager
