### ISSUE TITLE
Wizard errors out when in firmware installation step with Pixhawks

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#1738]
user report:

"The new setup wizard fails to get a stable firmware and reports an error 500. There's no way to get past that screen so I have to abort the setup wizard. My guess would be that this is because I use pixhawks, but idk."

**Comment by joaoantoniocardoso** [comment]
Seems the same as reported in https://github.com/bluerobotics/BlueOS-docker/issues/1722

**Comment by Williangalvani** [comment]
yeah, probably.
closing as duplicate of #1722
