### ISSUE TITLE
No external way for the user to update things outside bootstrap

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#175]
Currently, if the user needs to re-run install.sh, for example, it need to do that manually.
The recent changes to fix the LEDs pull-ups was a case where a install.sh re-run was needed.
Ideally we should have some way for the user to do that without sshing into rasp.

DAYS_TO_DEVELOP:5

**Comment by patrickelectric** [comment]
Related to #414

**Comment by Williangalvani** [comment]
This was implemented in #1034 and is done with the "blueos_startup_update" file.
