### ISSUE TITLE
we should be able to load qgc parameters in blueos

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#1750]

**Comment by ES-Alexander** [comment]
Not sure what you mean by this. Are you talking about loading QGC application settings from some kind of file, live-loading autopilot parameter changes made by an external source, or something else?

**Comment by Williangalvani** [comment]
qgc saves parameters in a slightly odd format including vehicle and system id. our parameter interface can't handle that
