### ISSUE TITLE
wizard: Loop path if no internet available

### ISSUE THREAD

**Issue by joaoantoniocardoso** [bluerobotics/BlueOS-docker#1755]
Simulating as if there's no internet available, the video below shows a natural flow from the wizard that puts the user in a loop, mostly because of the automatic page reload:

https://github.com/bluerobotics/BlueOS-docker/assets/5920286/0221cce8-a1c8-433d-b416-b8f30649a1ba

Related to #1746, as that will give another path option to the user.

**Comment by Williangalvani** [comment]
I believe this was fixed by #1746 ,
can you double-check? I'm unable to replicate

**Comment by joaoantoniocardoso** [comment]
Yeah, fixed :)
