### ISSUE TITLE
version-chooser: Deleted images do not disappear view

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1780]
And if you try to delete then again, you receive an (ugly) alert saying the image does not exist (which is true, it doesn't, but it sill appears there until you refresh the page).

https://github.com/bluerobotics/BlueOS-docker/assets/6551040/4e398625-87a8-4cad-a812-12f532680024

**Comment by joaoantoniocardoso** [comment]
I believe this is already fixed on current master.

**Comment by Williangalvani** [comment]
this was fixed in https://github.com/bluerobotics/BlueOS-docker/pull/1763
please re-open it it persists
