### ISSUE TITLE
bug: Beta 23, unable to load navigator board

### ISSUE THREAD

**Issue by RaulTrombin** [bluerobotics/BlueOS-docker#1801]
### Bug description

![image](https://github.com/bluerobotics/BlueOS-docker/assets/80598030/207f1f3d-f021-480e-9b48-edd239386e37)

A fresh install was made with beta 23, it boots without a navigator HAT attached,
On the next boots the user is unable to change the board.

Even changing to master, reset settings, etc.

### Steps to reproduce

fresh install a image and boot without navigator.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by Williangalvani** [comment]
it seems to be failing to detect the board. the the autopilotmanager logs

**Comment by RaulTrombin** [comment]
we can close this, it's an issue related only to the previous navigator board.
