### ISSUE TITLE
bug: Navigator i2c-1 not using maximum clock speed

### ISSUE THREAD

**Issue by RaulTrombin** [bluerobotics/BlueOS-docker#1802]
### Bug description

Navigator isn't using it's 1000000 capability on i2c-1 bus.

sudo vcdbg log msg 
```

006640.711: Loaded overlay 'i2c1'
006640.721: dtparam: baudrate=1000000
006643.563: Unknown dtparam 'baudrate' - ignored

```

check the clock:
echo -n "0x$(xxd -p /sys/class/i2c-adapter/i2c-1/of_node/clock-frequency)" | xargs printf "%d\n"

### Steps to reproduce

we need to add 
dtparam i2c_baudrate=1000000
to config.txt on config_board script.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by Williangalvani** [comment]
we should probably do this in #1765
