### ISSUE TITLE
Motor tests when in Auto mode are dangerous

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#1804]
We should put the vehicle in Manual mode before starting the test, otherwise if there's a mission in the vehicle, the motors will spin.

From @raimullin14:

"Just a heads up. I was disarmed in auto mode on cockpit and when I armed it in this window it resumed the mission in cockpit and started running the thrusters".

![image](https://github.com/bluerobotics/BlueOS-docker/assets/6551040/d01f6934-39fd-4aee-aa9d-780ad37541e5)

**Comment by patrickelectric** [comment]
It looks much more as a firmware problem than from our side, the firmware should not allow motor test in any mode besides MANUAL. @Williangalvani

**Comment by ES-Alexander** [comment]
It's a firmware _problem_, but given it's already the case in the current firmware version(s) it seems like it wouldn't hurt for BlueOS to just send a manual mode change before trying to do motor test stuff.

**Comment by Williangalvani** [comment]
Alternatively, we can disable motor test in modes other than manual

**Comment by patrickelectric** [comment]
Yes that's required, but a palliative solution for the real problem.
