### ISSUE TITLE
core: version chooser: sha information is not useful 

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#267]
The sha is not our git repository sha, or IMAGE ID, or CONTAINER ID, or dockerhub sha code.
Where they come from, who we should use, where are we going ?
![image](https://user-images.githubusercontent.com/1215497/119132233-d7575500-ba10-11eb-9b60-b949fc98ae07.png)

**Comment by Williangalvani** [comment]
That _is_ the image id
![image](https://user-images.githubusercontent.com/4013804/119139437-65373e00-ba19-11eb-9592-cbb9f847d1d2.png)

**Comment by patrickelectric** [comment]
Ok, but my point is that is not clear which sha is this, and how useful is this sha.
How we can compare it with github or dockerhub to know that we are running the latest version ?

**Comment by Williangalvani** [comment]
yeah, dockerhub is weird.
`docker image inspect 72814f1ef1cd`
actually shows a "RepoDigests" key, but the contents don't match dockerhub.
Maybe we're seeing 72814f1ef1cd? I can get back to this later.

**Comment by patrickelectric** [comment]
Ok, I believe that we should work to improve this.
I vote to add the information of our github tag, hash, build time and etc in the docker metadata and use it with others important shas in the webpage in an explicit and clear way.

**Comment by Williangalvani** [comment]
Yeah, it seems to be somewhat doable with [labels](https://nickjanetakis.com/blog/docker-tip-25-adding-metadata-to-your-docker-images-with-labels), I'll do some experimentation with it.

**Comment by Williangalvani** [comment]
fixed in #782

only displayed in pirate mode, only loaded for tags available both locally and remotely
