### ISSUE TITLE
CI: Provide .img files

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#366]
The .img file is a companion image for the raspberry pi 4

**Comment by patrickelectric** [comment]
https://github.com/Nature40/pimod

**Comment by Williangalvani** [comment]
I spent some time on this yesterday. It turns out that the docker step fails due to missing Systemd.
trying to launch the docker daemon manually fails due to missing cgroups.

Maybe running it on our pi4 CI could work? idk

**Comment by patrickelectric** [comment]
Done in #812
