### ISSUE TITLE
Deal with dockerhub rate-limiting

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#382]
Just got this:
docker.errors.APIError: 500 Server Error for http+docker://localhost/v1.41/images/create?tag=master&fromImage=bluerobotics%2Fcompanion-core: Internal Server Error ("toomanyrequests: You have reached your pull rate limit. You may increase the limit by authenticating and upgrading: https://www.docker.com/increase-rate-limit")

The rate limit right now is of 100 pulls in a 6h interval. There's more information at https://www.docker.com/increase-rate-limit.

**Comment by patrickelectric** [comment]
Just to make sure from, from a single client or for a single docker image ?

**Comment by patrickelectric** [comment]
Maybe we should keep track and warn our users ?
"You have requested to many requests to check for a new update, your actual limit is x of 100"

**Comment by Williangalvani** [comment]
each manifest download counts as a pull
We do one manifest pull for each tag in a remote when checking available tags.

**Comment by patrickelectric** [comment]
If'm not mistaken the plan was to have a "cache" for manifests or only fetch such manifest when necessary, no ?

**Comment by patrickelectric** [comment]
@Williangalvani we have fixed that with latest rework right ?

**Comment by patrickelectric** [comment]
#782

**Comment by Williangalvani** [comment]
yes!
