### ISSUE TITLE
Ardupilot loop is slipping a lot, triggering internal errors.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#398]
This is likely due to the scheduler.
A couple of things helped so far:

 - i2c at 1MHz helps a lot, but not 100%, it is also potentially unsafe (we need to check all datasheets and pull-ups)
 - Custom 4.9 PREEMPT kernel: worked nicely with i2c bauds of 400khz, with minor slips
 
 things to test still:
   - use isolcpu to allow ardupilot to run on it's own core of the Pi.
   - disable interruptions at the core ardupilot is running?
   - nice -20
   - proper preempt-rt patch

I think we should try to steer away from using a custom kernel, but it is good to know it is a solution.

**Comment by patrickelectric** [comment]
@Williangalvani that was fixed using a RT kernel right ?
Can you somehow document the process of creating a raspberry image with such kernel ?

**Comment by patrickelectric** [comment]
@Williangalvani is this still valid ?

**Comment by patrickelectric** [comment]
ping @Williangalvani

**Comment by patrickelectric** [comment]
We are using a normal linux image with a lower loop frequency on ardupilot
