### ISSUE TITLE
frontend: Add network speed test

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#448]
- [ ] Allow checking network speed
  - [x] with current wifi connection
  - [x] with current ethernet connection
  - [x] latency
  - [ ] with internet
  - [ ] with [iperf3](https://iperf.fr/) or similar tool

DAYS_TO_DEVELOP:2

**Comment by rafaellehmkuhl** [comment]
@patrickelectric should we close this one or just check all besides the iperf one?

**Comment by patrickelectric** [comment]
That was not entirely by #843, we still need to add a network test to get the internet speed on the vehicle.

**Comment by Williangalvani** [comment]
something like this would be nice later on
![Screenshot_20220425-195143](https://user-images.githubusercontent.com/4013804/165213847-a57b8842-eeb3-498f-92c9-f0df215fa5a1.png)

**Comment by patrickelectric** [comment]
This appears to be a great library to use and have real-time updates on the speed test on the frontend: https://pypi.org/project/aiotestspeed/

**Comment by patrickelectric** [comment]
Reference #1271
