### ISSUE TITLE
ardupilot-manager: Pixhawk4 vs Pixhawk1

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#452]
Apparently Pixhawk4 has a different `board_type` but uses the same `board_id` as Pixhawk1.

This is making the firmware-manager think they are the same board, but the Ardupilot Upload tool does not proceed with the firmware upload, thus reaching the timeout.

As we are probably going to have Pixhawk4 as a backup for Pixhawk1 (end of life), we should check for those differences and support it.

DAYS_TO_DEVELOP:3

**Comment by jaxxzer** [comment]
![image](https://user-images.githubusercontent.com/8315108/131564993-0dcb4c19-5c36-4ab5-9df0-610dcf1199d7.png)

**Comment by patrickelectric** [comment]
Just to make it clear, is this a problem related to our code or ArduPilot upload tool ?

**Comment by rafaellehmkuhl** [comment]
Our code.
The upload tool is correctly recognizing that this is a different board and we should use a proper firmware.
We think it's the same board (for us, any serial board is the same, currently).

**Comment by rafaellehmkuhl** [comment]
One thing we could do is to use the upload tool when detecting serial boards to correctly identify it's `board_id`, and set the correspondent board.

**Comment by rafaellehmkuhl** [comment]
I've just checked and their `board_id` is different. Pix1 is 9 and Pix4 is 50. Our current approach on the firmware manager is good, we just need to fix the serial board detector to treat different boards different.
