### ISSUE TITLE
frontend: disconnect still appears in multiple tabs when backend is back

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#618]
![image](https://user-images.githubusercontent.com/1215497/139101652-b6c6b809-04ae-4d02-a7dc-9f90dc8786c0.png)
![image](https://user-images.githubusercontent.com/1215497/139101793-74444fda-27f5-417d-97a6-b3256fc96328.png)

**Comment by rafaellehmkuhl** [comment]
@patrickelectric @Williangalvani @joaoantoniocardoso @ES-Alexander did any of you experienced that recently? I believe this stopped to happen at some point, but don't know when.

**Comment by patrickelectric** [comment]
Closing it until we have new reports
