### ISSUE TITLE
core: nginx: consider serving the web interface at :2770, or at least redirect it to :80

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#632]
people consistently try to use that

**Comment by ES-Alexander** [comment]
The original fix seems to be broken now - presumably since the update from `companion.local` to `blueos.local`.
It currently redirects to `%28blueos%7Ccompanion%29.local` and can't be reached.

A dynamic fix would be preferred over another hardcoded url, given we're planning to support a dynamic/customisable hostname in future. If that's not possible we'll need to remember this exists when we add that feature.

**Comment by rafaellehmkuhl** [comment]
> The original fix seems to be broken now - presumably since the update from `companion.local` to `blueos.local`. It currently redirects to `%28blueos%7Ccompanion%29.local` and can't be reached.
> 
> A dynamic fix would be preferred over another hardcoded url, given we're planning to support a dynamic/customisable hostname in future. If that's not possible we'll need to remember this exists when we add that feature.

Kind of thing that makes me think we should just dish the `companion.local` address.
Unnecessary maintenance. Everyone that flashes BlueOS knows it's doing it.

**Comment by patrickelectric** [comment]
> > The original fix seems to be broken now - presumably since the update from `companion.local` to `blueos.local`. It currently redirects to `%28blueos%7Ccompanion%29.local` and can't be reached.
> > A dynamic fix would be preferred over another hardcoded url, given we're planning to support a dynamic/customisable hostname in future. If that's not possible we'll need to remember this exists when we add that feature.
> 
> Kind of thing that makes me think we should just dish the `companion.local` address. Unnecessary maintenance. Everyone that flashes BlueOS knows it's doing it.

This is a retrocompatibility feature for people that uses old companion or follows any forum post related to Companion. This is indeed a maintenance thing, but we should stay with it for a couple of releases until we migrate the majority of our users. And if someone is talking about it (like Eliot in this issue), someone was able to catch it and report, so it's still a use case that we need to handle for now.

**Comment by rafaellehmkuhl** [comment]
> > > The original fix seems to be broken now - presumably since the update from `companion.local` to `blueos.local`. It currently redirects to `%28blueos%7Ccompanion%29.local` and can't be reached.
> > > A dynamic fix would be preferred over another hardcoded url, given we're planning to support a dynamic/customisable hostname in future. If that's not possible we'll need to remember this exists when we add that feature.
> > 
> > 
> > Kind of thing that makes me think we should just dish the `companion.local` address. Unnecessary maintenance. Everyone that flashes BlueOS knows it's doing it.
> 
> This is a retrocompatibility feature for people that uses old companion or follows any forum post related to Companion. This is indeed a maintenance thing, but we should stay with it for a couple of releases until we migrate the majority of our users. And if someone is talking about it (like Eliot in this issue), someone was able to catch it and report, so it's still a use case that we need to handle for now.

Just telling them to use blueos.local instead of companion.local seems like a better solution.

Just look at @Williangalvani's PR. Unnecessary maintenance, and don't solve the problem entirely.
