### ISSUE TITLE
Docker doesn't shutdown properly when rebooting

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#663]
This causes the PWM to act up when using a Navigator board, as ardusub is not stopped properly (it expects a signal to shutdown the PCA properly).

**Comment by patrickelectric** [comment]
Is there any way for us to fix that ?

**Comment by patrickelectric** [comment]
Is this still an issue ?

**Comment by Williangalvani** [comment]
The PCA issue is fixed AFAIR.
we could still have issues with corrupted files, as I think the containers are being killed instead of gracefully shut down (which they just don't know how to do).

**Comment by patrickelectric** [comment]
Can you put more in details how it was fixes ? Or just not replicable ?

**Comment by Williangalvani** [comment]
I haven't seen this anymore. This is the relevant PR: https://github.com/ArduPilot/ardupilot/pull/18635

It could also be that I just haven't rebooted the vehicle with motors on anymore (which is silly and shouldn't be allowed anyway).
