### ISSUE TITLE
Current state of multiple-cameras support

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#689]
On QGC: a patch like [this](https://github.com/mavlink/qgroundcontrol/compare/master...Williangalvani:joystickcamera?expand=1) (but hopefully better) is required to enable using the joystick to change cameras:
![image](https://user-images.githubusercontent.com/4013804/143293487-9b327cd9-0067-45db-a309-55f2f13f5c46.png)

The camera streams need to be set to 
udp://192.168.2.1:XXXX, where XXXX is any free udp port (I recommend udp://192.168.2.1:5600 and udp://192.168.2.1:5605)

MavlinkCameraManager is having issues communicating with the current settings, we should consider temporarily changing it to `mavlink-camera-manager --default-settings BlueROVUDP --mavlink udpout:192.168.2.1:14550` so it tries to communicate to qgc directly.

Here I used the PS4 joystick and used the "click on touchpad" button to switch streams, as it is button 20 which we can't use for ardusub commands. And yes, the touchpad button was also interpreted as a mouse click, which changes the focus from qgc in the video :man_shrugging: 

https://user-images.githubusercontent.com/4013804/143295102-615cdb05-dfc1-4bbb-a79f-f0f68fa0718a.mp4

**Comment by Williangalvani** [comment]
https://github.com/mavlink/qgroundcontrol/pull/10106 exposes the camera controls to the joystick

**Comment by Williangalvani** [comment]
this seems to affect QGC's hability to download vehicle parameters...

**Comment by patrickelectric** [comment]
@Williangalvani what is the status of this issue ?

**Comment by Williangalvani** [comment]
I believe all in here has been addressed. I'll close this.
