### ISSUE TITLE
Add some debugging capabilities for Ardupilot

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#717]
we could detect a debug binary and set up at least gdb server when launching. This part should be straight forward.
We could also display something in the frontend so the user knows they're using a debug binary.

**Comment by matt-bathyscope** [comment]
Would this only be for Linux Ardupilot builds or should this also work for Pixhawk (i.e., OpenOCD+GDB+SWD probe)?

**Comment by patrickelectric** [comment]
For now, only for Linux board would be great already
