### ISSUE TITLE
Add a mechanism for syncing clock time with topside

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#74]

**Comment by patrickelectric** [comment]
We could do that through QGC with the mavlink set time message.
Is there any better alternative ?

**Comment by Williangalvani** [comment]
That is fine, I meant the OS, though. I got reports of tlogs with bad timestamps in the companion due to a (10days) time drift of the pi clock

**Comment by patrickelectric** [comment]
Waiting for artifact: https://github.com/patrickelectric/linux2rest/releases/tag/v0.2.1
