### ISSUE TITLE
Video stream URLs with spaces are incorrectly accepted

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#746]
![image](https://user-images.githubusercontent.com/6551040/151596045-caa7241b-da69-4981-8f90-f17a162d73bb.png)

**Comment by patrickelectric** [comment]
That's still a valid url, a weird one, but valid, spaces will be converted to %20

**Comment by rafaellehmkuhl** [comment]
Closed as it's valid
