### ISSUE TITLE
core: frontent: wifi modal should hide "connect button" when connecting, and close automatically a few seconds after connecting.

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#761]

**Comment by patrickelectric** [comment]
It would be nice if we could provide the connection status:
Connecting..
Fetching ip address.. 
and etc

**Comment by rafaellehmkuhl** [comment]
> It would be nice if we could provide the connection status: Connecting.. Fetching ip address.. and etc

Created #979 to track this.

**Comment by rafaellehmkuhl** [comment]
> It would be nice if we could provide the connection status: Connecting.. Fetching ip address.. and etc

Tracked by #668
