### ISSUE TITLE
core: frontend: show current firmware version

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-docker#777]
### Current behaviour

The `General` and `Firmware` pages of `Autopilot` don't show the current firmware. Not knowing which firmware is running makes it harder to know what to update to, or whether an update is relevant/necessary.

### Expected or desired behaviour

One (or preferably both) pages should display the current firmware version on any connected board(s).

Ideally `General` would show all boards and their current firmwares, whereas the `Firmware` page should likely allow selecting the board to update, and show the current firmware on the currently selected board.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
We should provide the entire content of FWVersion
https://github.com/ArduPilot/ardupilot/blob/master/Tools/scripts/firmware_version_decoder.py#L83-L100
