### ISSUE TITLE
bug: frontend: sidebar scrollbar broken

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-docker#786]
### Bug description

When the sidebar menu options are expanded (or if the window is vertically shrunk) they go off the bottom of the browser. A scrollbar only seems to appear when the options are taller than the screen or something, instead of taller than the current window view, and the scrollbar that appears still doesn't give access to all the options/doesn't show the buttons at the bottom.

<img width="258" alt="Screen Shot 2022-02-10 at 11 48 28 pm" src="https://user-images.githubusercontent.com/25898329/153412356-cf87676b-07b9-41d5-8c89-7c6c6a158dc5.png"> <img width="263" alt="Screen Shot 2022-02-10 at 11 50 34 pm" src="https://user-images.githubusercontent.com/25898329/153412400-d5ee971a-d914-43a7-ab01-a982d4497430.png">

### Steps to reproduce

Method 1:
1. Expand both options in the sidebar while on a kinda short screen
2. Fail to access all the tools / the buttons at the bottom

Method 2:
1. Make your window really short
2. Achieve step 2 from Method 1

### Primary pain point(s)

No buttons at the bottom means I can't report bugs 😂 

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
@ES-Alexander I think I fixed that on #822. Please let me know if this was the case. The image is available under `rafaellehmkuhl/blueos-core:fix_main_menu`.

**Comment by ES-Alexander** [comment]
Confirmed - fixes the problem :-)
