### ISSUE TITLE
A lot of documentations are returning an "empty" page instead of the correct link

### ISSUE THREAD

**Issue by Williangalvani** [bluerobotics/BlueOS-docker#807]
### Bug description

![image](https://user-images.githubusercontent.com/4013804/154773653-59240032-8ecb-4081-9dd5-57ccc0f47736.png)

### Steps to reproduce

click the cable-guy docs link

### Primary pain point(s)

there's no way to navigate to the correct url without writing it down in the url.

We should detect the one under v1.0/docs, or load it programatically from the first url

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
Done in #825
