### ISSUE TITLE
bug: Hearbeat icon beating fine when only a camera is alive

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#838]
### Bug description

<img width="1284" alt="image" src="https://user-images.githubusercontent.com/6551040/156637093-5324c1af-16e9-498e-9f7c-74802882e125.png">

<img width="994" alt="image" src="https://user-images.githubusercontent.com/6551040/156637166-1993e0c0-34bc-42ef-8a63-92213a5280d8.png">

### Steps to reproduce

1. Upgrade Navigator firmware to Dev (which is broken)
2. Ardupilot-manager will fail to start the firmware and enter a restart loop
3. Watch the heartbit icon and Mavlink inspector

### Primary pain point(s)

User thinks everything is fine when it isn't.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
We should break the messages inside the frontend per vehicle/component, right now we don't have such control
