### ISSUE TITLE
bug: Service logs are not persistent between docker boots

### ISSUE THREAD

**Issue by rafaellehmkuhl** [bluerobotics/BlueOS-docker#839]
### Bug description

When docker restart, service logs are lost, probably because `/root/.cache/` is not binded.

<img width="1102" alt="image" src="https://user-images.githubusercontent.com/6551040/156637770-64f608c9-a273-409b-bdb8-b3aebc7cd312.png">

### Steps to reproduce

1.  Look at your service logs. There's always just one file. 

### Primary pain point(s)

If one power down BlueOS, the logs are lost.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
@Williangalvani for this one, should we add a bind to `startup.json.default`?

**Comment by Williangalvani** [comment]
yes

we also need a service/script that udaptes the user current settings.
