### ISSUE TITLE
bug: System Information service is a bit cooked

### ISSUE THREAD

**Issue by ES-Alexander** [bluerobotics/BlueOS-docker#932]
### Bug description

In [Available Services / System Information](http://blueos.local:6030):
- `udev` is slow to load
- `kernel` only works once per container restart
- `netstat` works, but takes over the service display until a page refresh
- `platform` doesn't work at all, and occasionally (seemingly if on it for long enough) blanks out the display until a page refresh

https://user-images.githubusercontent.com/25898329/160532982-c11fa204-4395-4002-ba8b-d3435127747c.mov

### Steps to reproduce

1. Go to [Available Services / System Information](http://blueos.local:6030)
2. Click around
3. Panik

### Primary pain point(s)

Broken services and interfaces make me sad :-(
I don't actually need this for anything right now.

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by patrickelectric** [comment]
kernel issue fixed in https://github.com/patrickelectric/linux2rest/pull/9.
Everything else is from the development UI that's not supposed to be accessible for users :)
But I'll rework it to make it better.
