### ISSUE TITLE
bug: Notification icon sayd that there is notifications but none is visible

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#953]
### Bug description

The notification widget says 11 but clicking on it says "No notifications"
![image](https://user-images.githubusercontent.com/1215497/161975075-94ad0bc2-15bd-4ce0-83af-c889fab2d8e6.png)

### Steps to reproduce

Of course, clicking on the gear icon, and toggling “Show old messages”, finally I can see them

![image](https://user-images.githubusercontent.com/1215497/161975028-581cd0aa-eb3d-4d9a-a306-c5ae70ccd91c.png)

### Primary pain point(s)

The number should reflect the number of notifications that the user will see once clicked. 

Original report: @joaoantoniocardoso 

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
@patrickelectric are you working on this one?
