### ISSUE TITLE
bug: nmea: not working

### ISSUE THREAD

**Issue by patrickelectric** [bluerobotics/BlueOS-docker#993]
### Bug description

![image](https://user-images.githubusercontent.com/1215497/164708062-554c2819-395b-4a4b-a06b-98ea0288ae37.png)

### Steps to reproduce

Connect to source of NMEA

### Primary pain point(s)

It breaks

### Prerequisites

- [X] I have checked to make sure that a similar request has not already been filed or fixed.

**Comment by rafaellehmkuhl** [comment]
Will take a look into this.
This was reported by Ryan?

**Comment by patrickelectric** [comment]
JM

**Comment by rafaellehmkuhl** [comment]
No idea what JM means.

**Comment by patrickelectric** [comment]
Validated to be working by JM (our distributor) as well.

**Comment by rafaellehmkuhl** [comment]
Niceeeeee
